name: moneynote4
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:

  analyzer: ^6.2.0
  bubble: ^1.2.1
  cupertino_icons: ^1.0.2

  device_info_plus: ^8.0.0
  fab_circular_menu: ^1.0.2
  fl_chart: ^0.55.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16
  flutter_polyline_points: ^1.0.0
  flutter_riverpod: ^2.4.8
  flutter_slidable: ^2.0.0
  flutter_sliding_tutorial: ^2.0.0+1
  font_awesome_flutter: ^10.2.1
  freezed_annotation: ^2.2.0
  geolocator: ^9.0.2
  go_router: ^12.0.0
  google_maps_flutter: ^2.2.5
  hooks_riverpod: ^2.1.1
  http: ^0.13.5
  intl: ^0.17.0
  json_annotation: ^4.7.0
  riverpod_annotation: ^2.3.2
  scroll_to_index: ^3.0.1
  shared_preferences:
  soundpool: ^2.3.0
  tab_container: ^2.0.0
  table_calendar: ^3.0.8
  uuid: ^3.0.7
  vibration: ^1.7.6

dev_dependencies:

  build_runner:
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  json_serializable: ^6.5.4

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
    - assets/csv/

flutter_native_splash:
  image: "assets/images/money.png"
  color: "212121"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher.png"

  adaptive_icon_background: "#212121"
  adaptive_icon_foreground: "assets/images/launcher.png"
